import { createContext, useContext, useState, type ReactNode } from "react";

type Lang = "en" | "sn";

const translations: Record<Lang, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.about": "About",
    "nav.suites": "Suites",
    "nav.gallery": "Gallery",
    "nav.local-area": "Local Area",
    "nav.faq": "FAQ",
    "nav.contact": "Contact",
    "nav.book-direct": "Book Direct",
    "hero.tagline": "Boutique Guest House • Braeside",
    "hero.subtitle": "Where premium security meets continuous solar power.",
    "hero.cta-book": "Book Your Stay",
    "hero.cta-rooms": "View Our Rooms",
    "booking.title": "Pre-Draft Your Harare Stay",
    "booking.select-suite": "Select Suite",
    "booking.check-in": "Check-In",
    "booking.check-out": "Check-Out",
    "booking.guests": "Guests",
    "booking.submit": "Draft on WhatsApp Booking Desk",
    "booking.total": "Total Estimate",
    "booking.nights": "nights",
    "booking.add-shuttle": "Airport Shuttle ($15)",
    "booking.add-breakfast": "Continental Breakfast ($8/day)",
    "booking.preview": "WhatsApp Draft Preview",
    "about.title": "A Sanctuary in Braeside",
    "about.subtitle": "Your Home Away From Home in Harare",
    "suites.title": "Our Suites",
    "gallery.title": "Our Gallery",
    "faq.title": "Frequently Asked Questions",
    "contact.title": "Contact Us",
    "contact.address": "Address",
    "contact.phone": "Phone",
    "contact.email": "Email",
    "contact.whatsapp": "Chat on WhatsApp",
    "portal.title": "Guest Portal",
    "portal.welcome": "Welcome to City View Guest House",
    "portal.wifi-title": "WiFi Access",
    "portal.wifi-name": "Network: CityView_Guest",
    "portal.wifi-pass": "Password: Braeside2024!",
    "portal.checkin-title": "Check-In / Check-Out",
    "portal.checkin-time": "Check-in: 14:00 (flexible upon request)",
    "portal.checkout-time": "Check-out: 11:00 (late checkout available)",
    "portal.rules-title": "House Rules",
    "portal.rules-quiet": "Quiet hours: 22:00 – 07:00",
    "portal.rules-smoking": "Smoking in designated outdoor areas only",
    "portal.rules-visitors": "Visitors must register at reception",
    "portal.food-title": "Local Food Delivery",
    "portal.food-1": "Munchies Express — +263 78 123 4567",
    "portal.food-2": "Braeside Kitchen — +263 77 234 5678",
    "portal.food-3": "Harare Meals on Wheels — +263 71 345 6789",
    "portal.transfer-title": "Airport Transfer",
    "portal.transfer-info": "Contact Holyfield on +263 78 009 6836 to arrange pickup. $15 one way.",
    "portal.emergency-title": "Emergency Contacts",
    "portal.emergency-host": "Host: Holyfield (Mr H. Moyo) — +263 78 009 6836",
    "portal.review-title": "Enjoyed Your Stay?",
    "portal.review-cta": "Leave a Google Review",
    "portal.gate-title": "Enter Your Booking Code",
    "portal.gate-hint": "Your booking code was provided at check-in. For example: CV-2024",
    "portal.gate-submit": "Access Portal",
    "portal.gate-error": "Invalid code. Please check your booking confirmation or contact the host.",
    "rate.night": "/night",
    "footer.copyright": "City View Guest House. All rights reserved.",
  },
  sn: {
    "nav.home": "Musha",
    "nav.about": "Nezvedu",
    "nav.suites": "Dzimba",
    "nav.gallery": "Mifananidzo",
    "nav.local-area": "Nharaunda",
    "nav.faq": "Mibvunzo",
    "nav.contact": "Tibatsirane",
    "nav.book-direct": "Bhuka Nhasi",
    "hero.tagline": "Imba YeVashanyi • Braeside",
    "hero.subtitle": "Nzvimbo yakachengeteka ine solar power inogara iripo.",
    "hero.cta-book": "Bhuka Nzvimbo Yako",
    "hero.cta-rooms": "Ona Dzimba Dzedu",
    "booking.title": "Ronga Kugara Kwako Harare",
    "booking.select-suite": "Sarudza Imba",
    "booking.check-in": "Zuva Rokupinda",
    "booking.check-out": "Zuva Rokubuda",
    "booking.guests": "Vaeni",
    "booking.submit": "Tumira pa WhatsApp Booking Desk",
    "booking.total": "Mutengo Wose",
    "booking.nights": "usiku",
    "booking.add-shuttle": "Kutakwa kuAirport ($15)",
    "booking.add-breakfast": "Chirairo Chemangwanani ($8/zuva)",
    "booking.preview": "WhatsApp Draft Preview",
    "about.title": "Nzvimbo Yekuzorora muBraeside",
    "about.subtitle": "Imba Yako Kure NeMusha muHarare",
    "suites.title": "Dzimba Dzedu",
    "gallery.title": "Mifananidzo Yedu",
    "faq.title": "Mibvunzo Inowanzo Bvunzwa",
    "contact.title": "Tibatsirane",
    "contact.address": "Kero",
    "contact.phone": "Runhare",
    "contact.email": "Email",
    "contact.whatsapp": "Taura paWhatsApp",
    "portal.title": "Portal YeVaeni",
    "portal.welcome": "Tinokugamuchirai paCity View Guest House",
    "portal.wifi-title": "WiFi",
    "portal.wifi-name": "Network: CityView_Guest",
    "portal.wifi-pass": "Password: Braeside2024!",
    "portal.checkin-title": "Kupinda / Kubuda",
    "portal.checkin-time": "Kupinda: 14:00 (zvinogona kuchinja)",
    "portal.checkout-time": "Kubuda: 11:00 (zvinogona kunonoka)",
    "portal.rules-title": "Mitemo YeImba",
    "portal.rules-quiet": "Nguva dzekunyarara: 22:00 – 07:00",
    "portal.rules-smoking": "Kusvuta kunobvumidzwa panze chete",
    "portal.rules-visitors": "Vashanyi vanofanira kunyora pa reception",
    "portal.food-title": "Kudya Kwomunharaunda",
    "portal.food-1": "Munchies Express — +263 78 123 4567",
    "portal.food-2": "Braeside Kitchen — +263 77 234 5678",
    "portal.food-3": "Harare Meals on Wheels — +263 71 345 6789",
    "portal.transfer-title": "Kutakwa kuAirport",
    "portal.transfer-info": "Fonera Holyfield pa +263 78 009 6836 kuronga. $15 rwendo rumwe.",
    "portal.emergency-title": "Nhamba Dzekukurumidzira",
    "portal.emergency-host": "Muridzi: Holyfield (Mr H. Moyo) — +263 78 009 6836",
    "portal.review-title": "Wakanakidzwa Nekugara Kwako?",
    "portal.review-cta": "Isa Ongororo paGoogle",
    "portal.gate-title": "Isa Code Yekubhuka",
    "portal.gate-hint": "Code yako yakapihwa pacheck-in. Semuenzaniso: CV-2024",
    "portal.gate-submit": "Pinda Portal",
    "portal.gate-error": "Code haina kushanda. Tarisa booking yako kana kuti fonera muridzi.",
    "rate.night": "/usiku",
    "footer.copyright": "City View Guest House. Kodzero dzese dzakachengetedzwa.",
  },
};

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const LangContext = createContext<LangContextType>({
  lang: "en",
  setLang: () => {},
  t: (k: string) => k,
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("en");
  const t = (key: string) => translations[lang][key] || key;
  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
